apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-xgo2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-xgo2
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-xgo2
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-xgo2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-xgo2
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-cysd-tenant/appstudio/dc-metro-map-xgo2@sha256:50f76c112648b2aef82265dbfdb08b45feb64a9a525611f4cb9b2bdeecb5df61
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
